config-version: 7

debug-mode: false # enable to log additional debug information to the console

proxy-id:
  id: "proxy-1" # unique id of this proxy instance, must be different for each proxy in the network. will be ignored if auto-generate is true
  auto-generate: true # set to true to auto-generate a random unique id on first startup (recommended)

redis:
  host: "localhost"
  port: 6379
  username: "default" # if you don't know what this is, leave it as "default" or if your Redis server has no username, set to blank
  password: "ver!yS€cureP@ssw0rd" # set to blank if no password is required
  database: 0 # if you don't know what this is, leave it at 0
  connectionPoolSize: 10 # maximum number of connections in the pool. Do not change this unless you know what you are doing.
  connectionTimeout: 2000 # in milliseconds
  # ssl options
  ssl: false # set to true if your Redis server requires SSL
  allowSelfSignedCertificates: false # set to true if you want to allow self-signed SSL certificates
  trustStorePath: "" # path to your trust store file, leave blank to use the default Java trust store
  trustStorePassword: "" # password for your trust store, leave blank if not applicable

anti-vpn:
  enabled: false # enable to block VPN connections. This will use the https://ipquery.io/ to check if a player's IP is a known VPN or proxy. Note that this is not 100% accurate and can sometimes block legitimate players, so use with caution and make sure to whitelist any false positives.
  webhook: "https://discord.com/api/webhooks/" # discord webhook url, leave blank to disable webhook notifications for blocked VPN connections
  send-in-thread: false # whether to send the webhook message in a thread or not
  thread-id: "" # if send-in-thread is true, the id of the thread to send the message in. leave blank to send in the main channel

cloud-support:
  enabled: false # this will enable support for cloud systems like CloudNet, SimpleCloud or VulpesCloud. It will replace the proxy-id with the cloud system's server id automatically
  cloud-system: "cloudnet" # can be "cloudnet", "simplecloud" or "vulpescloud"

update-check:
  enabled: true
  notify-admins: true # notify users with the permission "redivelocity.admin.updatecheck" about available updates
  check-interval: 3600 # in seconds

playercount-sync:
  enabled: true
  use-backend-server-count: false # if enabled, the global player count will be the sum of players on the specified backend servers instead of the proxies
  backend-server-names: # list of backend server names to include in the player count (only used if use-backend-server-count is true). add an entry contain '*' to include all backend servers. regex is supported
    - "server-1"
    - "server-2"

playerversion-check:
  enabled: false # enable to restrict player versions
  bypass-permission: "redivelocity.admin.versionbypass" # permission that allows players to bypass the version check and join the proxy with any version
  allowed-versions: # array of allowed Minecraft versions (protocol versions)
    - 773 # Minecraft 1.21.10

# This restores normal Velocity behavior where a player can only be connected to the network one time and not multiple
# For example if you have a Lobby and a SMP, players won't be able to be connected to the lobby and the SMP at the same time, when they have
# 2 instances of Minecraft running. This is recommended to prevent issues with plugins that rely on unique player connections, but it can be disabled if you want to allow players to be connected to multiple proxies at the same time (for example if you have a BungeeCord and a Velocity proxy running at the same time and want players to be able to connect to both with the same Minecraft instance)
# It is recommended to keep this on false unless you have a specific use case for allowing players to be connected to multiple proxies at the same time, as it can cause issues with plugins that rely on unique player connections and can also cause issues with player data management and other features that rely on unique player connections.
# Note that if you set this to true, players can be on your network multiple times at the same time if they have 2 instances of Minecraft running and they are lucky enough to connect to different proxies with each instance and one instance is on your lobby and the other on the SMP
# And most important: THIS IS NOT 100% SAFE! When you have PERFECT timing, you can still have 2 instances online, but the chance of this happening is very low and it requires a lot of luck, so it's not something you should worry about, but it's still worth mentioning that this is not a perfect solution to allow players to be connected to multiple proxies at the same time, but it's the best solution we have for now without implementing a more complex system to track player connections across proxies and prevent duplicates in a more reliable way.
allow-same-player-on-multiple-proxies: false # Recommended: false
ignore-same-players-when-transfer: false # if true, any incomming transfers will bypass the check described above. could be useful if you have a eu region and a us region, but could be unsafe if you have a lobby and a smp, as players could be on both at the same time. Recommended: false, please only enable this if you know what you are doing and have a specific use case for it.

# Most of this requires your Redis to be persistent, so make sure you have a persistent Redis setup, otherwise this will not work and will cause issues with player connections and data management.
# This is mostly here to provide default if no value is found in Redis
login-configuration:
  enabled: true
  max-players: 187 # maximum number of players allowed to connect to the proxy at the same time. if the limit is reached, new players will be denied access and receive a message. can be modified ingame too
  enforce-max-players: true # if true, the proxy will enforce the max-players limit and deny new connections when the limit is reached. if false, the proxy will allow new connections even if the limit is reached. Recommended: true
  max-players-bypass-permission: "redivelocity.maxplayers.bypass" # permission that allows players to bypass the max-players limit and join the proxy even if the limit is reached. Recommended: redivelocity.maxplayers.bypass
  use-motd: true # if true, redivelocity now handles the motd and will display it to players when they ping the proxy. if false, the proxy will use the default motd from velocity or any other plugin that handles the motd.
  forced-motd: "" # if set, the proxy will always use this motd instead of a random one. can be used to force a specific motd. leave blank to disable. can be set ingame too
  motds:
    motd-1:
      content: "&6&lRediVelocity &7- &e&lProxy Network<br>&7&lPlayers: &e%player_count% &7&lMax: &e%max_players%"
      playerInfo: "good info"
      maintenance: false # if true, the motd can be used when in maintenance mode
    motd-2:
      content: "&6&lRediVelocity &7- &e&lProxy Network 2<br>&7&lPlayers: &e%player_count% &7&lMax: &e%max_players%"
      playerInfo: "good info (2)"
      maintenance: false # if true, the motd can be used when in maintenance mode
    motd-maintenance-1:
      content: "&6&lRediVelocity &7- &e&lProxy Network<br>&cMaintenance"
      playerInfo: "good info"
      protocolText: "&bRediVelocity"
      maintenance: true # if true, the motd can be used when in maintenance mode
    motd-maintenance-2:
      content: "&6&lRediVelocity &7- &e&lProxy Network 2<br>&cMaintenance"
      playerInfo: "good info (2)"
      protocolText: "&bRediVelocity 2"
      maintenance: true # if true, the motd can be used when in maintenance mode
  maintenance:
    enabled: false # enable to put the proxy in maintenance mode, this will prevent players from joining the proxy and display the maintenance motd instead. this can be toggle ingame too
    forced-motd: "" # if set, the proxy will always use this motd instead of a random one when in maintenance mode. can be used to force a specific motd. leave blank to disable. can be set ingame too
    bypass-permission: "redivelocity.maintenance.bypass" # permission that allows players to bypass maintenance mode and join the proxy while in maintenance mode.

commands: # enable or disable specific commands
  find: true # find players across all proxies and display some information about them