config-version: 1

debug-mode: false # enable to log additional debug information to the console

proxy-id:
  id: "proxy-1" # unique id of this proxy instance, must be different for each proxy in the network. will be ignored if auto-generate is true
  auto-generate: true # set to true to auto-generate a random unique id on first startup (recommended)

redis:
  host: "localhost"
  port: 6379
  username: "default" # if you don't know what this is, leave it as "default" or if your Redis server has no username, set to blank
  password: "ver!yS€cureP@ssw0rd" # set to blank if no password is required
  database: 0 # if you don't know what this is, leave it at 0

cloud-support:
  enabled: false # this will enable support for cloud systems like CloudNet, SimpleCloud or VulpesCloud. It will replace the proxy-id with the cloud system's server id automatically
  cloud-system: "cloudnet" # can be "cloudnet", "simplecloud" or "vulpescloud"

update-check:
  enabled: true
  notify-admins: true # notify users with the permission "redivelocity.update" about available updates
  check-interval: 3600 # in seconds

playercount-sync:
  enable: true
  use-backend-server-count: false # if enabled, the global player count will be the sum of players on the specified backend servers instead of the proxies
  backend-server-names: # list of backend server names to include in the player count (only used if use-backend-server-count is true). add an entry contain '*' to include all backend servers. regex is supported
    - "server-1"
    - "server-2"

playerversion-check:
  enabled: true
  allowed-versions:
    - 773

commands: # enable or disable specific commands
  send: true # an override for the /send command that also supports sending players from different proxies
  alert: true # a global chat alert command
  alert-raw: true # a global chat alert command that supports raw message formatting using MiniMessage or legacy formatting
  find: true # find players across all proxies and display some information about them