name: Publish Modrinth

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Set version from release tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}  # remove leading v
          echo "version=$VERSION" >> gradle.properties
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build with Gradle ShadowJar
        run: ./gradlew clean shadowJar

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 9Z08wH8I
          name: ${{ github.event.release.name }}
          version: ${{ env.VERSION }}
          changelog: ${{ github.event.release.body }}
          channel: release
          featured: true
          loaders: |-
            velocity
          game-versions: |-
            1.21.x
            1.20.x
            1.19.x
            1.18.x
            1.17.x
            1.16.x
            1.15.x
            1.14.x
            1.13.x
            1.12.x
            1.11.x
            1.10.x
            1.9.x
            1.8.9
          files: build/libs/RediVelocity-${{ env.VERSION }}.jar